/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppStudentIndexRouteImport } from './routes/app.student.index'
import { Route as AppParentIndexRouteImport } from './routes/app.parent.index'
import { Route as AppLecturerIndexRouteImport } from './routes/app.lecturer.index'
import { Route as AppStudentResultsRouteImport } from './routes/app.student.results'
import { Route as AppStudentParentsRouteImport } from './routes/app.student.parents'
import { Route as AppStudentCoursesRouteImport } from './routes/app.student.courses'
import { Route as AppLecturerCoursesRouteImport } from './routes/app.lecturer.courses'
import { Route as AppAdminNotificationsRouteImport } from './routes/app.admin.notifications'
import { Route as AppAdminEnrollmentsRouteImport } from './routes/app.admin.enrollments'
import { Route as AppAdminCoursesRouteImport } from './routes/app.admin.courses'
import { Route as AppParentResultsStudentIdRouteImport } from './routes/app.parent.results.$studentId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentIndexRoute = AppStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => AppRoute,
} as any)
const AppParentIndexRoute = AppParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => AppRoute,
} as any)
const AppLecturerIndexRoute = AppLecturerIndexRouteImport.update({
  id: '/lecturer/',
  path: '/lecturer/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentResultsRoute = AppStudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentParentsRoute = AppStudentParentsRouteImport.update({
  id: '/student/parents',
  path: '/student/parents',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentCoursesRoute = AppStudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppLecturerCoursesRoute = AppLecturerCoursesRouteImport.update({
  id: '/lecturer/courses',
  path: '/lecturer/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEnrollmentsRoute = AppAdminEnrollmentsRouteImport.update({
  id: '/admin/enrollments',
  path: '/admin/enrollments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCoursesRoute = AppAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppParentResultsStudentIdRoute =
  AppParentResultsStudentIdRouteImport.update({
    id: '/parent/results/$studentId',
    path: '/parent/results/$studentId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/enrollments': typeof AppAdminEnrollmentsRoute
  '/app/admin/notifications': typeof AppAdminNotificationsRoute
  '/app/lecturer/courses': typeof AppLecturerCoursesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/parents': typeof AppStudentParentsRoute
  '/app/student/results': typeof AppStudentResultsRoute
  '/app/lecturer/': typeof AppLecturerIndexRoute
  '/app/parent/': typeof AppParentIndexRoute
  '/app/student/': typeof AppStudentIndexRoute
  '/app/parent/results/$studentId': typeof AppParentResultsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/enrollments': typeof AppAdminEnrollmentsRoute
  '/app/admin/notifications': typeof AppAdminNotificationsRoute
  '/app/lecturer/courses': typeof AppLecturerCoursesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/parents': typeof AppStudentParentsRoute
  '/app/student/results': typeof AppStudentResultsRoute
  '/app/lecturer': typeof AppLecturerIndexRoute
  '/app/parent': typeof AppParentIndexRoute
  '/app/student': typeof AppStudentIndexRoute
  '/app/parent/results/$studentId': typeof AppParentResultsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/courses': typeof AppAdminCoursesRoute
  '/app/admin/enrollments': typeof AppAdminEnrollmentsRoute
  '/app/admin/notifications': typeof AppAdminNotificationsRoute
  '/app/lecturer/courses': typeof AppLecturerCoursesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/parents': typeof AppStudentParentsRoute
  '/app/student/results': typeof AppStudentResultsRoute
  '/app/lecturer/': typeof AppLecturerIndexRoute
  '/app/parent/': typeof AppParentIndexRoute
  '/app/student/': typeof AppStudentIndexRoute
  '/app/parent/results/$studentId': typeof AppParentResultsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/welcome'
    | '/app/profile'
    | '/app/'
    | '/app/admin/courses'
    | '/app/admin/enrollments'
    | '/app/admin/notifications'
    | '/app/lecturer/courses'
    | '/app/student/courses'
    | '/app/student/parents'
    | '/app/student/results'
    | '/app/lecturer/'
    | '/app/parent/'
    | '/app/student/'
    | '/app/parent/results/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/welcome'
    | '/app/profile'
    | '/app'
    | '/app/admin/courses'
    | '/app/admin/enrollments'
    | '/app/admin/notifications'
    | '/app/lecturer/courses'
    | '/app/student/courses'
    | '/app/student/parents'
    | '/app/student/results'
    | '/app/lecturer'
    | '/app/parent'
    | '/app/student'
    | '/app/parent/results/$studentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/welcome'
    | '/app/profile'
    | '/app/'
    | '/app/admin/courses'
    | '/app/admin/enrollments'
    | '/app/admin/notifications'
    | '/app/lecturer/courses'
    | '/app/student/courses'
    | '/app/student/parents'
    | '/app/student/results'
    | '/app/lecturer/'
    | '/app/parent/'
    | '/app/student/'
    | '/app/parent/results/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/': {
      id: '/app/student/'
      path: '/student'
      fullPath: '/app/student/'
      preLoaderRoute: typeof AppStudentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parent/': {
      id: '/app/parent/'
      path: '/parent'
      fullPath: '/app/parent/'
      preLoaderRoute: typeof AppParentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lecturer/': {
      id: '/app/lecturer/'
      path: '/lecturer'
      fullPath: '/app/lecturer/'
      preLoaderRoute: typeof AppLecturerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/results': {
      id: '/app/student/results'
      path: '/student/results'
      fullPath: '/app/student/results'
      preLoaderRoute: typeof AppStudentResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/parents': {
      id: '/app/student/parents'
      path: '/student/parents'
      fullPath: '/app/student/parents'
      preLoaderRoute: typeof AppStudentParentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/courses': {
      id: '/app/student/courses'
      path: '/student/courses'
      fullPath: '/app/student/courses'
      preLoaderRoute: typeof AppStudentCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lecturer/courses': {
      id: '/app/lecturer/courses'
      path: '/lecturer/courses'
      fullPath: '/app/lecturer/courses'
      preLoaderRoute: typeof AppLecturerCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/notifications': {
      id: '/app/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/app/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/enrollments': {
      id: '/app/admin/enrollments'
      path: '/admin/enrollments'
      fullPath: '/app/admin/enrollments'
      preLoaderRoute: typeof AppAdminEnrollmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/courses': {
      id: '/app/admin/courses'
      path: '/admin/courses'
      fullPath: '/app/admin/courses'
      preLoaderRoute: typeof AppAdminCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parent/results/$studentId': {
      id: '/app/parent/results/$studentId'
      path: '/parent/results/$studentId'
      fullPath: '/app/parent/results/$studentId'
      preLoaderRoute: typeof AppParentResultsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminCoursesRoute: typeof AppAdminCoursesRoute
  AppAdminEnrollmentsRoute: typeof AppAdminEnrollmentsRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppLecturerCoursesRoute: typeof AppLecturerCoursesRoute
  AppStudentCoursesRoute: typeof AppStudentCoursesRoute
  AppStudentParentsRoute: typeof AppStudentParentsRoute
  AppStudentResultsRoute: typeof AppStudentResultsRoute
  AppLecturerIndexRoute: typeof AppLecturerIndexRoute
  AppParentIndexRoute: typeof AppParentIndexRoute
  AppStudentIndexRoute: typeof AppStudentIndexRoute
  AppParentResultsStudentIdRoute: typeof AppParentResultsStudentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminCoursesRoute: AppAdminCoursesRoute,
  AppAdminEnrollmentsRoute: AppAdminEnrollmentsRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppLecturerCoursesRoute: AppLecturerCoursesRoute,
  AppStudentCoursesRoute: AppStudentCoursesRoute,
  AppStudentParentsRoute: AppStudentParentsRoute,
  AppStudentResultsRoute: AppStudentResultsRoute,
  AppLecturerIndexRoute: AppLecturerIndexRoute,
  AppParentIndexRoute: AppParentIndexRoute,
  AppStudentIndexRoute: AppStudentIndexRoute,
  AppParentResultsStudentIdRoute: AppParentResultsStudentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
