/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LecturerIndexRouteImport } from './routes/lecturer.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LecturerScoresRouteImport } from './routes/lecturer.scores'
import { Route as LecturerCoursesRouteImport } from './routes/lecturer.courses'
import { Route as LecturerAnnouncementsRouteImport } from './routes/lecturer.announcements'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin.enrollments'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AppStudentIndexRouteImport } from './routes/app.student.index'
import { Route as AppParentIndexRouteImport } from './routes/app.parent.index'
import { Route as AppStudentResultsRouteImport } from './routes/app.student.results'
import { Route as AppStudentParentsRouteImport } from './routes/app.student.parents'
import { Route as AppStudentCoursesRouteImport } from './routes/app.student.courses'
import { Route as AppParentPreferencesRouteImport } from './routes/app.parent.preferences'
import { Route as AppParentResultsStudentIdRouteImport } from './routes/app.parent.results.$studentId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerIndexRoute = LecturerIndexRouteImport.update({
  id: '/lecturer/',
  path: '/lecturer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerScoresRoute = LecturerScoresRouteImport.update({
  id: '/lecturer/scores',
  path: '/lecturer/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerCoursesRoute = LecturerCoursesRouteImport.update({
  id: '/lecturer/courses',
  path: '/lecturer/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerAnnouncementsRoute = LecturerAnnouncementsRouteImport.update({
  id: '/lecturer/announcements',
  path: '/lecturer/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/admin/enrollments',
  path: '/admin/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentIndexRoute = AppStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => AppRoute,
} as any)
const AppParentIndexRoute = AppParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentResultsRoute = AppStudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentParentsRoute = AppStudentParentsRouteImport.update({
  id: '/student/parents',
  path: '/student/parents',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentCoursesRoute = AppStudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppParentPreferencesRoute = AppParentPreferencesRouteImport.update({
  id: '/parent/preferences',
  path: '/parent/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppParentResultsStudentIdRoute =
  AppParentResultsStudentIdRouteImport.update({
    id: '/parent/results/$studentId',
    path: '/parent/results/$studentId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/profile': typeof AppProfileRoute
  '/lecturer/announcements': typeof LecturerAnnouncementsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/scores': typeof LecturerScoresRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/app/parent/preferences': typeof AppParentPreferencesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/parents': typeof AppStudentParentsRoute
  '/app/student/results': typeof AppStudentResultsRoute
  '/app/parent/': typeof AppParentIndexRoute
  '/app/student/': typeof AppStudentIndexRoute
  '/app/parent/results/$studentId': typeof AppParentResultsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/profile': typeof AppProfileRoute
  '/lecturer/announcements': typeof LecturerAnnouncementsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/scores': typeof LecturerScoresRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/lecturer': typeof LecturerIndexRoute
  '/app/parent/preferences': typeof AppParentPreferencesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/parents': typeof AppStudentParentsRoute
  '/app/student/results': typeof AppStudentResultsRoute
  '/app/parent': typeof AppParentIndexRoute
  '/app/student': typeof AppStudentIndexRoute
  '/app/parent/results/$studentId': typeof AppParentResultsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/profile': typeof AppProfileRoute
  '/lecturer/announcements': typeof LecturerAnnouncementsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/scores': typeof LecturerScoresRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/app/parent/preferences': typeof AppParentPreferencesRoute
  '/app/student/courses': typeof AppStudentCoursesRoute
  '/app/student/parents': typeof AppStudentParentsRoute
  '/app/student/results': typeof AppStudentResultsRoute
  '/app/parent/': typeof AppParentIndexRoute
  '/app/student/': typeof AppStudentIndexRoute
  '/app/parent/results/$studentId': typeof AppParentResultsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/welcome'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/notifications'
    | '/admin/users'
    | '/app/announcements'
    | '/app/profile'
    | '/lecturer/announcements'
    | '/lecturer/courses'
    | '/lecturer/scores'
    | '/admin/'
    | '/app/'
    | '/lecturer/'
    | '/app/parent/preferences'
    | '/app/student/courses'
    | '/app/student/parents'
    | '/app/student/results'
    | '/app/parent/'
    | '/app/student/'
    | '/app/parent/results/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/welcome'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/notifications'
    | '/admin/users'
    | '/app/announcements'
    | '/app/profile'
    | '/lecturer/announcements'
    | '/lecturer/courses'
    | '/lecturer/scores'
    | '/admin'
    | '/app'
    | '/lecturer'
    | '/app/parent/preferences'
    | '/app/student/courses'
    | '/app/student/parents'
    | '/app/student/results'
    | '/app/parent'
    | '/app/student'
    | '/app/parent/results/$studentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/welcome'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/notifications'
    | '/admin/users'
    | '/app/announcements'
    | '/app/profile'
    | '/lecturer/announcements'
    | '/lecturer/courses'
    | '/lecturer/scores'
    | '/admin/'
    | '/app/'
    | '/lecturer/'
    | '/app/parent/preferences'
    | '/app/student/courses'
    | '/app/student/parents'
    | '/app/student/results'
    | '/app/parent/'
    | '/app/student/'
    | '/app/parent/results/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LecturerAnnouncementsRoute: typeof LecturerAnnouncementsRoute
  LecturerCoursesRoute: typeof LecturerCoursesRoute
  LecturerScoresRoute: typeof LecturerScoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LecturerIndexRoute: typeof LecturerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/': {
      id: '/lecturer/'
      path: '/lecturer'
      fullPath: '/lecturer/'
      preLoaderRoute: typeof LecturerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/scores': {
      id: '/lecturer/scores'
      path: '/lecturer/scores'
      fullPath: '/lecturer/scores'
      preLoaderRoute: typeof LecturerScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/courses': {
      id: '/lecturer/courses'
      path: '/lecturer/courses'
      fullPath: '/lecturer/courses'
      preLoaderRoute: typeof LecturerCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/announcements': {
      id: '/lecturer/announcements'
      path: '/lecturer/announcements'
      fullPath: '/lecturer/announcements'
      preLoaderRoute: typeof LecturerAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/admin/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/student/': {
      id: '/app/student/'
      path: '/student'
      fullPath: '/app/student/'
      preLoaderRoute: typeof AppStudentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parent/': {
      id: '/app/parent/'
      path: '/parent'
      fullPath: '/app/parent/'
      preLoaderRoute: typeof AppParentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/results': {
      id: '/app/student/results'
      path: '/student/results'
      fullPath: '/app/student/results'
      preLoaderRoute: typeof AppStudentResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/parents': {
      id: '/app/student/parents'
      path: '/student/parents'
      fullPath: '/app/student/parents'
      preLoaderRoute: typeof AppStudentParentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/courses': {
      id: '/app/student/courses'
      path: '/student/courses'
      fullPath: '/app/student/courses'
      preLoaderRoute: typeof AppStudentCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parent/preferences': {
      id: '/app/parent/preferences'
      path: '/parent/preferences'
      fullPath: '/app/parent/preferences'
      preLoaderRoute: typeof AppParentPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parent/results/$studentId': {
      id: '/app/parent/results/$studentId'
      path: '/parent/results/$studentId'
      fullPath: '/app/parent/results/$studentId'
      preLoaderRoute: typeof AppParentResultsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppParentPreferencesRoute: typeof AppParentPreferencesRoute
  AppStudentCoursesRoute: typeof AppStudentCoursesRoute
  AppStudentParentsRoute: typeof AppStudentParentsRoute
  AppStudentResultsRoute: typeof AppStudentResultsRoute
  AppParentIndexRoute: typeof AppParentIndexRoute
  AppStudentIndexRoute: typeof AppStudentIndexRoute
  AppParentResultsStudentIdRoute: typeof AppParentResultsStudentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppParentPreferencesRoute: AppParentPreferencesRoute,
  AppStudentCoursesRoute: AppStudentCoursesRoute,
  AppStudentParentsRoute: AppStudentParentsRoute,
  AppStudentResultsRoute: AppStudentResultsRoute,
  AppParentIndexRoute: AppParentIndexRoute,
  AppStudentIndexRoute: AppStudentIndexRoute,
  AppParentResultsStudentIdRoute: AppParentResultsStudentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  WelcomeRoute: WelcomeRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  LecturerAnnouncementsRoute: LecturerAnnouncementsRoute,
  LecturerCoursesRoute: LecturerCoursesRoute,
  LecturerScoresRoute: LecturerScoresRoute,
  AdminIndexRoute: AdminIndexRoute,
  LecturerIndexRoute: LecturerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
